services:
  - type: web
    name: ai-receptionist-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: "3000"
      - key: PUBLIC_BASE_URL
        value: ""   # leave blank on first deploy; set after you get the Render URL
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: USER_FORWARD_NUMBER
        value: "+15551234567"
      - key: FIRESTORE_COLLECTION
        value: "voicemails"
